name: observatory

on:
  pull_request:
    paths:
      - ".github/workflows/observatory.yml"
      - "Cargo.*"
      - "observatory/**"
  push:
    branches:
      - main

defaults:
  run:
    working-directory: observatory

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: "-Dwarnings"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.72 # MSRV
          - stable
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - run: cargo build
